# Generated by Django 5.0 on 2023-12-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='complete_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateField(blank=True),
        ),
    ]
