# Generated by Django 5.0 on 2023-12-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_card_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateField(verbose_name='Due Date'),
        ),
    ]
