# Generated by Django 5.0 on 2023-12-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateField(),
        ),
    ]
